version: "3.9"

services:
  ingest-api:
    image: ingest-api
    build:
      context: ./ingest_api
      
  db-api:
    image: db-api
    build:
      context: ./dbapi

  worker-python:
    image: worker-python
    build:
      context: ./workers
      dockerfile: worker-python/Dockerfile

  worker-db:
    image: worker-db
    build:
      context: ./workers
      dockerfile: worker-db/Dockerfile
  
  pipeline-registry:
    image: pipeline-registry
    build:
      context: ./pipeline_registry
      dockerfile: Dockerfile
