version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - testnet

  worker-python:
    image: worker-python
    container_name: worker-python
    depends_on:
      - rabbitmq
    networks:
      - testnet
    volumes:
      - ./config_files/worker-python:/app/src/config
      - ./artifacts_files/python-scripts:/app/scripts
  worker-db:
    image: worker-db
    container_name: worker-db
    depends_on:
      - rabbitmq
    networks:
      - testnet
    volumes:
      - ./config_files/worker-db:/app/src/config

  ingest-api:
    image: ingest-api
    container_name: ingest-api
    ports:
      - "3003:3003"    
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      PORT: 3003
    networks:
      - testnet
  
  db-api:
    image: db-api
    container_name: db-api
    ports:
      - "3004:3004"    
    networks:
      - testnet

  pipeline-registry:
    image: pipeline-registry
    container_name: pipeline-registry
    ports:
      - "3002:3002"
    networks:
      - testnet
    volumes:
      - ./artifacts_files/pipelines:/app/src/pipelines


networks:
  testnet:
    external: true
